### ISSUE TITLE
[issue][blocker] the web module build fails

### ISSUE THREAD

**Issue by SoulElle** [Damianofds/taskmanager#10]
Following the instructions, the `mvn clean install -Pweb` fails as soon as the tests start for the **services** component.
![unnamed-3](https://user-images.githubusercontent.com/8139700/46607521-96c99800-cb01-11e8-8606-fad409af8a00.png)
![unnamed-2](https://user-images.githubusercontent.com/8139700/46607533-a9dc6800-cb01-11e8-9db0-b4b807d74936.png)
![unnamed-1](https://user-images.githubusercontent.com/8139700/46607563-bd87ce80-cb01-11e8-9a1f-b5d2ee715bc1.png)
**full log** - [build-failure.rtf.zip](https://github.com/Damianofds/taskmanager/files/2455774/build-failure.rtf.zip)

If I avoid running tests with `mvn clean install -Pweb -DskipTests`, then the build succeeds, but starting the generated endpoints.jar via `java -jar path/to/endpoints.jar` immediately crashes with another exception.
```
java -jar ~/.m2/repository/it/fds/taskmanager/endpoints/0.1-SNAPSHOT/endpoints-0.1-SNAPSHOT.jar
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/web/socket/config/annotation/AbstractWebSocketMessageBrokerConfigurer
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:801)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:699)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:622)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:575)
	at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:177)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:143)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.springframework.web.socket.config.annotation.AbstractWebSocketMessageBrokerConfigurer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 14 more
```

**Comment by SoulElle** [comment]
My guess is I either don't have something important installed on the system although I did follow the instructions to get all the required components installed (git, JDK8, Maven3, Postgresql, Docker). Or the build system is somehow misconfigured as in the class paths are not defined.

**Comment by Damianofds** [comment]
Ciao Elena,

I tried to build again the project first on on my machine, then on a
colleague machine who never worked on that project and then using an empty
maven repo, all builds were successful.
I tried both the master and buggy-taskmanager branches, both are building
fine.

These are my main env settings:

```
fds@ubuntu ~/work/code/taskmanager (master) $ mvn -version
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_161, vendor: Oracle Corporation
Java home: /usr/lib/jvm/jdk1.8.0_161/jre
Default locale: en_AU, platform encoding: UTF-8
OS name: "linux", version: "4.10.0-28-generic", arch: "amd64", family:
"unix"
```

Did you try to build the project using an empty maven repo? maybe you
downloaded a corrupted jar file during your first build?
Let me know!

Regards,
Damiano

Il giorno lun 8 ott 2018 alle ore 14:10 SoulElle <notifications@github.com>
ha scritto:

**Comment by SoulElle** [comment]
Hi Damiano,
Thanks for the input Meanwhile, I think I've identified the root cause of the problem. Turned out I had two JDKs installed:
```
/usr/libexec/java_home -V
Matching Java Virtual Machines (2):
    11, x86_64:	"OpenJDK 11"	/Library/Java/JavaVirtualMachines/openjdk-11.jdk/Contents/Home
    1.8.0_181, x86_64:	"Java SE 8"	/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home
```

And obviously OpenJDK 11 was used:
```
mvn --version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T20:33:14+02:00)
Maven home: /usr/local/Cellar/maven/3.5.4/libexec
Java version: 11, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/openjdk-11.jdk/Contents/Home
Default locale: en_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"
```

After switching to 8 via `export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)`, the build process succeeds just fine.

The endpoints app still crashes at start, but it clearly goes way beyond the original crash and I'll report the problem in a separate issue.

Thanks anyway.

**Comment by Damianofds** [comment]
Ciao Elena,

Do you still have problem in running the endpoints?


Regards,
Damiano

**Comment by SoulElle** [comment]
Hi Damiano, no, endpoint and scheduler are running fine after I switched to jdk 1.8 and updated the properties with the correct database name too for the tests. Thanks for the support.

**Comment by Damianofds** [comment]
ok Great!
